#!/bin/bash
plug_vim="$HOME/.vim/autoload/plug.vim"
if [ ! -f "$plug_vim" ]; then
    curl -fLo "$plug_vim" --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
mkdir -p "$HOME/.vim/swapfiles"
