#!/bin/bash
plug_vim="$HOME/.vim/autoload/plug.vim"
if [ ! -f "$plug_vim" ]; then
    curl -fLo "$plug_vim" --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
mkdir -p "$HOME/.vim/swapfiles"

venv_dir="$HOME/.vim/python3-venv"
if [ ! -d "$venv_dir" ]; then
    python3 -m venv --prompt "(vim)" "$venv_dir"
    "$venv_dir/bin/pip" install --upgrade pip setuptools
    "$venv_dir/bin/pip" install neovim jedi
fi
